AllCops:
  Exclude:
    - 'bin/bundle'

AllCops:
  Exclude:
    - vendor/bundle/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
